### ISSUE TITLE
zoneminder: /usr/lib64 exists in filesystem

### ISSUE THREAD

**Issue by troywill** [troywill/zoneminder-aur#5]
https://www.google.com/?gws_rd=ssl#q=/usr/lib64+exists+in+filesystem&tbs=qdr:w

https://www.archlinux.org/news/update-filesystem-201301-1-and-glibc-217-2-together/

**Comment by cspenceiv** [comment]
As of 1.28.0, including -DZM_PERL_SUBPREFIX=/lib/perl5 in the cmake flags forces the problem files to install in /usr/lib instead of /usr/lib64. This error comes up because /usr/lib64 is a symlink to /usr/lib.

This is an issue that we will run into with any package installed with pacman. Pacman no longer tolerates installation of package components into symlink directories (http://allanmcrae.com/2014/12/pacman-4-2-released/). It was the solution to avoid the mess it was creating for the package manager when detecting conflicts.

As a side note: The INSTALL file included with ZoneMinder says that a leading slash is not needed, but without it, the libraries get thrown into a strange directory. A bug report has been submitted to look into the slash issue (https://github.com/ZoneMinder/ZoneMinder/issues/677).

**Comment by troywill** [comment]
Fixed in PKGBUILD and uploaded as zoneminder.1.28.0-8 to AUR, thanks. zoneminder-git package also uploaded.
